name: n8n-mcp
version: "0.0.1"
slug: n8nmcp
description: n8n-mcp server for managing n8n instances
url: "https://github.com/DTidey/n8n-mcp"
arch:
  - aarch64
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/czlonkowski/n8n-mcp:latest"
